title: Redrive
# description:  Ke
show_downloads: true
google_analytics:
theme: jekyll-theme-tactile
github:
  server_url: "https://github.com/tomatopickle/Redrive_Docs/releases/download/0.1.1/Redrive.Server.zip"
  client_url: "https://github.com/tomatopickle/Redrive_Docs/releases/download/0.1.1/redrive-release.apk"
